# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u8c46\u74e3subject')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u56fe\u4e66\u540d')),
                ('content', models.TextField(blank=True, null=True, verbose_name='\u56fe\u4e66\u8be6\u60c5')),
                ('menu_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u56fe\u4e66\u5206\u7c7b')),
            ],
            options={
                'ordering': ('-id',),
                'db_table': 'douban_book',
                'verbose_name': '\u56fe\u4e66\u4fe1\u606f\u8868',
            },
        ),
    ]
